Fix: Modify spacing between title, description, and CTA button
apeunit/unit-a-landing-page pull request #80
Opened 2023-02-03 11:23 UTC by alain-kubwayo

## Describe your changes
Changed spacing between title and description and reduced gap between `schedule call` button and description on mobile screen
## Issue ticket number and link
- ID: 067
- Link: [Notion](https://www.notion.so/apeunit/Fix-ContactUs-section-f5e8a266f660441db2f686d72028c68e)

## Tasks completed
- [x] Change spacing between title and description
- [x] Reduce gap between `schedule call` button and description on mobile screen
 
## Tasks not completed
- None

## Screenshots (if needed)

2023-02-03 14:09 UTC, Ntwali-Josue requested changes
Hey @alain-kubwayo, great work on implementing the fixes. I have highlighted a few changes to improve and your PR will be good to be approved. Check them down below:

2023-02-03 14:09 UTC, Ntwali-Josue commented on components/ui/Typography.jsx
> +        <p className={`font-normal leading-4.95 md:leading-7.5 text-4.5 md:text-6 -tracking-0.015 ${className}`}>{children}</p>
- Pull changes from the origin `dev` branch to have the updated `Paragraph` component.

2023-02-03 15:12 UTC, alain-kubwayo commented on components/sections/ContactUs.jsx
>                  <Heading2 className="text-center text-white text-11.75">Ready to talk about your project?</Heading2>
Thanks for catching that.

2023-02-07 13:34 UTC, mhenriette requested changes
@alain-kubwayo great Job on the changes made. however, I left a small comment, please check it out.

2023-02-07 13:34 UTC, mhenriette commented on components/sections/ContactUs.jsx
>              <LargeButton text="Schedule a call" styleSpan="mt-0.13" hasArrow={true} redirectLink="mailto:u2467@apeunit.com" />
the button text should have a font size of  20px on the mobile screens , i suggest you use the right component of **Heading4**

2023-02-07 14:14 UTC, Ntwali-Josue commented on components/ui/Typography.jsx
> +        <p className={`font-normal leading-6.75 md:leading-7.5 text-4.5 md:text-6 -tracking-0.015 ${className}`}>{children}</p>
Good job on fixing this `tracking` 💯

2023-02-07 14:15 UTC, Ntwali-Josue approved these changes
Great work @alain-kubwayo

2023-02-07 14:36 UTC, mhenriette approved these changes
Looks Good!!

2023-02-07 14:37 UTC, merged