Fix: Fixing line height
apeunit/unit-a-landing-page pull request #87
Opened 2023-02-09 12:52 UTC by Delyc

## Describe your changes
Fixing line height on who we are section

## Issue ticket number and link
- ID: 
- Link: 

## Tasks completed
- [x] Fixing line height on who we are section

 
## Tasks not completed
- None

## Screenshots (if needed)

2023-02-09 17:50 UTC, alain-kubwayo approved these changes
Looks good!

2023-02-13 05:51 UTC, Ntwali-Josue requested changes
Hey @Delyc, good work on fixing the line height and colors of the `What We Do` section. There is one requested change inside the `tailwind.config.js`, work on it for your PR to be ready for approval.

2023-02-13 05:51 UTC, Ntwali-Josue commented on tailwind.config.js
> +        9: "2.25rem",
By default, we do have this line-height value in Tailwind, so you don't need to add it here.

2023-02-14 08:49 UTC, mhenriette approved these changes
Looks Good!!

2023-02-14 08:55 UTC, Ntwali-Josue approved these changes

2023-02-14 08:55 UTC, merged